title: Jianmi
description: 一个不知名码农，从事后端开发工作
author: Jianmi
avatar: /avatar.png
email: xushouxin.sam@gmail.com
skin: daylight
lang: zh-cmn-Hans

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

remote-theme: ngzhio/jekyll-theme-hamilton

paginate: 10

exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec
  - favicon_package_v0.16

