title: Jianmi
description: jianmi的个人博客，如有写的不对的话，还请指教！
author: Jianmi
avatar: /logo.png
email: xushouxin.sam@gmail.com
skin: daylight

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

remote-theme: ngzhio/jekyll-theme-hamilton

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ngzhio
  card: summary
logo: logo.png
social:
  name: Jianmi
  links:
    - https://www.zhihu.com/people/xu-shou-xin-33
    - https://github.com/jianmi-xu
lang: en
